esphome:
  name: pool-temp
  platform: ESP8266
  board: esp12e

wifi:
  ssid: "xxxxx" #wifi ssid
  password: "xxxxx" #wifi password
  fast_connect: true

  ap:
    ssid: "Pool-Temp Fallback Hotspot"
    password: "xxxxx" #fallback hotspot password

captive_portal:

logger:

ota:
  password: "xxxxx" #ota password

dallas:
  - pin: 4

sensor:
  - platform: dallas
    address: xxxxx #dallas sensor address
    name: "Pool Temperature"

mqtt:
  broker: xxx.xxx.xxx.xxx #mqtt broker ip address
  username: xxxxx #mqtt username
  password: xxxxx #mdtt password
  discovery: true
  discovery_retain: true
  topic_prefix: /homeassistant
  log_topic: /esp/pool/temperature
  birth_message:
   topic: /esp/pool/temperature
   payload: ""
  will_message:
   topic: /esp/pool/temperature
   payload: ""

deep_sleep:
  run_duration: 5s
  sleep_duration: 20min
