esphome:
  name: window-sensor
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "xxxxx" #wifi ssid
  password: "xxxxx" #wifi password
  fast_connect: true

  ap:
    ssid: "Window-Sensor Fallback Hotspot"
    password: "xxxxx" #fallback hotspot password

mqtt:
  broker: xxx.xxx.xxx.xxx #mqtt broker ip address
  username: xxxxx #mqtt username
  password: xxxxx #mqtt password
  discovery: true
  discovery_retain: true

captive_portal:

logger:

ota:
  password: "xxxxx" #ota password

binary_sensor:
  - platform: status
    name: "Window Status"
  - platform: gpio
    pin:
      number: 14
      mode: INPUT_PULLDOWN
      inverted: True
    name: "door"
    device_class: door

deep_sleep:
  run_duration: 5s
  sleep_duration: 360min
  wakeup_pin: 14
  wakeup_pin_mode: INVERT_WAKEUP
